## local 환경
#
#spring:
#  profiles:
#    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#---
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: health,info
---
spring:
  profiles: set1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: set2

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
